trigger:
 - master
stages:
 - stage: Build
   displayName: Create build artifact
   jobs:
     - job: BuildArtifact
       pool: MYLAPTOP
       steps:
         - script: C:\Users\VIJAY\AppData\Local\UiPath\app-21.4.3\UiPath.Executor pack $(Build.SourcesDirectory)\project.json -o $(Build.ArtifactStagingDirectory)\ -v 1.0.$(Build.BuildNumber)
           displayName: "Build the artifact"
         - publish: $(Build.ArtifactStagingDirectory)
            artifact:drop